### ISSUE TITLE
Scope and plans?

### ISSUE THREAD

**Issue by itsdfish** [jshahbazi/Leabra.jl#1]
Hello,

Thank you for putting this package together.  As I was looking through Leabra, I thought Julia might be a good language choice, and then I came across your repo.  Go seems like a reasonable choice, but Julia has the advantage of a larger scientific computing ecosystem. 

I am curious about the completeness and scope of the package. What are your future plans?

**Comment by jshahbazi** [comment]
Hello @itsdfish!  Sorry for taking so long to respond.  I don't have any plans to continue this further.  I showed it to Dr. O'Reilly and he was interested in it, and its gotten a number of clones since it was created, but I've just moved on in my work.  I'd be happy to let someone else pick it up, though.

As far as completeness, its mostly just a conversion of the basic Leabra algorithm that was implemented in Matlab by Sergio Verduzco.  It is not the latest version of the algorithm, but in my opinion it gives a good idea of what the algorithm does.  And it is much, much faster than Go or Matlab.  I think Julia is a great language for it - it provides ease of use and speed.  There is still much more optimization that can be done as well.

**Comment by itsdfish** [comment]
Thank you for the update and no problem. Right now I am learning the semantic pointer architecture, but there is some chance that I will turn my focus to Leabra in the future. If I am able to understand it in sufficient detail, I would be interested in extending your package. 

Good to hear that the Julia version is already faster, even without all of the optimizations in place. That does sound promising.
